name: advanced-python
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - jupyterlab
  - notebook
  - jupyter_contrib_nbextensions
  - matplotlib
  - scikit-learn  # for the dataset
  - seaborn  # for the dataset
  - matplotlib
  - numpy
  - pandas
  - pip
  - uv
  - scipy
  - hist
  - mplhep
  - scienceplots
  - numexpr
  - pip:
      - zfit
      - jupyterlab-rise  # for jupyter notebook presentations
