name: tutorials

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:

jobs:
  notebooks:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 8
      fail-fast: False
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Run notebooks on OS ${{ runner.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell

      - shell: bash -l {0}
        name: Install dependencies
        run: |
          uv pip install pytest pytest-xdist nbval
      - name: Run notebooks
        run: |
          pytest --nbval-lax --dist loadscope -n auto
