name: tutorials

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:

jobs:
  notebooks:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 8
      fail-fast: False
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Run notebooks on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          uv pip install pytest pytest-xdist nbval
      - name: Run notebooks
        shell: bash -el {0}
        run: |
          pytest --nbval-lax --dist loadscope -n auto --ignore=session1


  pre-commit:
    name: pre-commit fixes (cleans notebooks etc.)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
      - uses: pre-commit/action@v3.0.1
